name: Spiritual Life Coaching
favicon: null
layout_spectrum: 0.024724874179810286
typography_spectrum: 0.7113676087465137
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9131751186214387
  lightness: 0.5107293867040426
  saturation: 0.657756089232862
  rhythmicContrast: 0.2893777859862894
purpose: []
